export const appIds = [
  "finder",
  "soundboard",
  "internet-explorer",
  "chats",
  "textedit",
  "paint",
  "photo-booth",
  "life-photos",
  "minesweeper",
  "videos",
  "ipod",
  "karaoke",
  "synth",
  "spotify",
  "substack",
  "cursor",
  "pc",
  "terminal",
  "applet-viewer",
  "control-panels",
  "admin",
] as const;

export type AppId = (typeof appIds)[number];
